name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'src/SCFirstOrderLogic.Documentation/**'

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest

    steps:

    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2
    
    # Set up .NET
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    # publishes Blazor project to the release folder
    - name: Publish .NET Core Project
      run: dotnet publish src/SCFirstOrderLogic.Documentation/SCFirstOrderLogic.Documentation.csproj -c Release -o release --nologo
    
    # changes the base-tag in index.html from '/' to 'BlazorGitHubPagesDemo' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to BlazorGitHubPagesDemo
      run: sed -i 's/<base href="\/" \/>/<base href="\/SCFirstOrderLogic\/" \/>/g' release/wwwroot/index.html
    
    # copy index.html to 404.html to serve the same file when a file is not found
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
     
    # copy to github pages sources
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot